#!/usr/bin/env tsx
/**
 * Drift gate for the docs-owned generators.
 *
 *   pnpm verify:generated
 *
 * Re-runs `gen:api` + `gen:sdk` into a scratch copy of `generated/` and fails
 * if the result differs from what is committed. That catches two things CI
 * otherwise ships silently:
 *
 *   1. someone hand-edited a file under `generated/`;
 *   2. an upstream source (the OpenAPI spec, an SDK repo's `docs/`) moved and
 *      nobody regenerated.
 *
 * The `marketplace`-owned mirrors (CLI + MCP reference, cli-commands.json) are
 * NOT re-run here — their generator lives in the shipeasy repo and needs the
 * Commander/MCP source tree. Those are pushed, and gated by that repo's own
 * pre-push hook.
 */
import { execFileSync } from "node:child_process";
import { cpSync, mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { GENERATED, MIRRORS, ROOT } from "./generated-map";

const scratch = mkdtempSync(join(tmpdir(), "shipeasy-docs-verify-"));
const backup = join(scratch, "generated");
cpSync(GENERATED, backup, { recursive: true });

let failed = false;
try {
  // Order matters: gen-llms stitches the MIRRORED tree, so the reference pages
  // the other two produce have to be in place under content/docs first.
  const steps: [string, string[]][] = [
    ["gen-api-reference.ts", []],
    ["gen-sdk-reference.ts", []],
    ["sync-generated.ts", ["--allow-missing"]],
    ["gen-llms.ts", []],
  ];
  for (const [script, args] of steps) {
    console.log(`verify:generated: running ${script}…`);
    execFileSync("pnpm", ["exec", "tsx", join("scripts", script), ...args], {
      cwd: ROOT,
      stdio: "inherit",
    });
  }

  const owned = MIRRORS.filter((m) => m.owner === "docs").map((m) => `generated/${m.from}`);
  const diff = execFileSync("git", ["status", "--porcelain", "--", ...owned], {
    cwd: ROOT,
    encoding: "utf8",
  }).trim();

  if (diff) {
    failed = true;
    console.error(
      `\nverify:generated: DRIFT — regeneration changed committed output:\n\n${diff}\n\n` +
        `Either an upstream source moved (commit the regenerated files), or a\n` +
        `generated file was hand-edited (it must not be — see generated/README.md).`,
    );
  } else {
    console.log("verify:generated: no drift.");
  }
} finally {
  if (failed) {
    // Leave the regenerated bytes in the tree so the author can just commit
    // them; only tell them where the pre-run copy went.
    console.error(`verify:generated: pre-run copy kept at ${backup}`);
  } else {
    rmSync(scratch, { recursive: true, force: true });
  }
}

process.exit(failed ? 1 : 0);
